---
- name: Lua | Update Pacman cache
  ansible.builtin.pacman:
    update_cache: true
  become: true

- name: Lua | Install Lua
  ansible.builtin.pacman:
    name: "{{ item }}"
  become: true
  loop:
    - lua
    - luarocks
    - luajit

- name: Lua | Gather installed lua rocks
  ansible.builtin.command: luarocks list
  register: rocks
  changed_when: false
  check_mode: false

# - name: Lua | Install Lua modules
#   ansible.builtin.command:
#     cmd: luarocks install {{ item }} --local
#   loop:
#     - luabitop
#   when: item not in rocks.stdout