---
- name: DotFiles Config
  hosts: localhost
  connection: local

  pre_tasks:

    - name: Detect Host User
      ansible.builtin.import_tasks: prereq/whoami.yml
      tags:
        - always


  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) | sort }}"
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always

    - name: Ensure wallpapers directory exists
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/roles/wallpapers"
        state: directory
        mode: "0755"

        
    - name: Copy wallpapers
      ansible.builtin.copy:
        src: /path/to/wallpapers/
        dest: "{{ ansible_user_dir }}/.config/wallpapers/"
        mode: "0644"
        directory_mode: "0755"
        force: yes
